import { Student } from './student.js'
import { createStudentArray } from './arrayCreator.js'
import { Renderer } from './renderer.js'

disableDarkModeByDefault()

let tbody = document.querySelector('tbody')

let students = await createStudentArray()
let renderer = new Renderer()
tbody.innerHTML = renderer.renderTable(students)


// ---------------------------------
//      CRUD functions
// ---------------------------------

document.querySelector('#add-new-student-btn').addEventListener('click', addNewStudent)

function addNewStudent () {

    let stud = new Student(
        '', // ID will be generated by the backend
        document.querySelector('#input-name').value,
        document.querySelector('#input-isActive').value === 'true',
        document.querySelector('#input-birthYear').value,
        document.querySelector('#input-connections').value,
        document.querySelector('#input-completedCredits').value,
        document.querySelector('#input-activeSemesterCount').value,
        document.querySelector('#input-image').value
    )

    // console.log(stud)
    // console.log(JSON.stringify(stud))

    // https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_json_data
    fetch("https://practiceapi.nikprog.hu/Student", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(stud),
        })
        .then((response) => response.json())
        .then((data) => {
            console.log("Success:", data)

            // add response data as new Student object to the array
            students.push(new Student(
                data.id,
                data.name,
                data.isActive,
                data.birthYear,
                data.connections,
                data.completedCredits,
                data.activeSemesterCount,
                data.image
            ))
            
            console.log("STUDENTS:",students)
            
            // re-render everything
            tbody.innerHTML = renderer.renderTable(students)
        })
        .catch((error) => {
            console.error("Error:", error)
        });
}


// ---------------------------------
//      Sorting functions
// ---------------------------------
document.querySelector('#sort-by-age-btn').addEventListener('click', sortBy)
document.querySelector('#sort-by-active-btn').addEventListener('click', sortBy)
document.querySelector('#sort-by-name-btn').addEventListener('click', sortBy)

function sortBy (param) {
    let sortByValue = param.target.dataset.param

    if(sortByValue === 'birthYear' || sortByValue === 'isActive')
        students.sort((a,b) => { return a[sortByValue] - b[sortByValue] })
    else if(sortByValue === 'name')
        students.sort((a,b) => { return a[sortByValue].localeCompare(b[sortByValue]) })
    
    tbody.innerHTML = renderer.renderTable(students)
}


// ------------------------
//      CSS handlers
// ------------------------
document.querySelector('#flexSwitchCheckDefault').addEventListener('click', switchMode)

function disableDarkModeByDefault () {
    document.styleSheets[1].disabled = true
}

function switchMode () {
    document.styleSheets[1].disabled = !document.styleSheets[1].disabled
}